### ISSUE TITLE
template과 wrapper selector string 일관성 및 유연성

### ISSUE THREAD

**Issue by ligeek** [beoreoji/pilDialog#1]
pilDialog 잘 사용하다가 문득 생각이 나서 이슈생성합니다.

```javascript
$.pilDialog.create({
    template : 'dialogTemplate',
    wrapper: $('#container'),
});
```
이런식으로 template과, wrapper의 value 값이 상이하다보니
사용함에 있어서 헛갈리는 경우가 많아요 :(

template, wrapper가 jquery의 $(node|css-selector)동작방식과 비슷하게 받게끔되면 좋겠습니다.

```javascript
$.pilDialog.create({
    template: '#dialogTemplate', // or template: document.getElementById('dialogTemplate')
    wrapper: '#container', // or wrapper: document.getElementById('container')
});
```

두개의(node|css-selector)를 모두 수용하면 특정 콜백안에서 this로 값을 전달할때나, 좀더 유연하게 사용할 수 있을 것 같아 보입니다(~~그런 상황이 일어날 경우가 별로 없겠지만~~)

**Comment by beoreoji** [comment]
좋은 생각인듯.. 풀리퀘스트 기다릴게요 ㅋㅋ
